routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();

Route::get('/', function () {
    return redirect('login');
});

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware' =>['auth','admin']],function() {


    Route::get('/categories', 'CategoryController@index');




    Route::get('/admin', 'AdminController@index')->name('admin');


    Route::get('/file-manager', function () {
        return view('backend.layouts.file-manager');
    })->name('file-manager');
// user route
    Route::resource('users', 'UsersController');
// Banner
    Route::resource('banner', 'BannerController');
// Brand
    Route::resource('brand', 'BrandController');
// Profile
    Route::get('/profile', 'AdminController@profile')->name('admin-profile');
    Route::post('/profile/{id}', 'AdminController@profileUpdate')->name('profile-update');
// Category
    Route::resource('/category', 'CategoryController');

    Route::resource('/variety', 'varietyController');
// Product
    Route::resource('/product', 'ProductController');
// Ajax for sub category
    Route::post('/category/{id}/child', 'CategoryController@getChildByParent');
// POST category
    Route::resource('/post-category', 'PostCategoryController');
// Post tag
    Route::resource('/post-tag', 'PostTagController');
// Post
    Route::resource('/post', 'PostController');
// Message
    Route::resource('/message', 'MessageController');
    Route::get('/message/five', 'MessageController@messageFive')->name('messages.five');

// Order
    Route::resource('/order', 'OrderController');
// Shipping
    Route::resource('/shipping', 'ShippingController');
// Coupon
    Route::resource('/coupon', 'CouponController');
// Settings
    Route::get('settings', 'AdminController@settings')->name('settings');
    Route::post('setting/update', 'AdminController@settingsUpdate')->name('settings.update');

// Notification
    Route::get('/notification/{id}', 'NotificationController@show')->name('admin.notification');
    Route::get('/notifications', 'NotificationController@index')->name('all.notification');
    Route::delete('/notification/{id}', 'NotificationController@delete')->name('notification.delete');
// Password Change
    Route::get('change-password', 'AdminController@changePassword')->name('change.password.form');
    Route::post('change-password', 'AdminController@changPasswordStore')->name('change.password');



});

app/variety.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class variety extends Model
{
    protected $fillable=['title','slug','summary','photo','status','parent_id'];

    public function parent_info(){
        return $this->hasOne('App\variety','id','status');
    }

    public static function getAllCategory(){
        return  variety::orderBy('id','DESC')->with('parent_info')->paginate(10);
    }
}

app/Http/Controllers/varietyController.php
<?php

namespace App\Http\Controllers;
use App\Variety;
use Illuminate\Http\Request;
use App\Models\Category;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class varietyController extends Controller
{
    public function index()
    {
        $category=Variety::getAllCategory();

        // return $category;

        return view('backend.variety.index')->with('categories',$category);
    }

    public function create()
    {
        $parent_cats=Variety::orderBy('title','ASC')->get();
        $category=Category::where('is_parent',1)->get();
        return view('backend.variety.create')->with('parent_cats',$parent_cats)->with('categories',$category);
    }

    public function store(Request $request)
    {
        // return $request->all();
        $this->validate($request,[
            'title'=>'string|required',
            'summary'=>'string|nullable',
//            'photo'=>'required|max:2048',
            'status'=>'required|in:active,inactive',
           // 'is_parent'=>'sometimes|in:1',
            'parent_id'=>'required',
        ]);
        $data= $request->all();


        $slug=Str::slug($request->title);
        $count=Variety::where('slug',$slug)->count();
        if($count>0){
            $slug=$slug.'-'.date('ymdis').'-'.rand(0,999);
        }

//        $image_original = $request->file('photo');
//
//        $image = time().'.'.$request->photo->getClientOriginalName();
//        $data['photo'] = $image;
        $data['slug']= $slug;
//        $data['is_parent']=$request->input('is_parent',0);


        $status=Variety::create($data);

        if($status){
            request()->session()->flash('success','Variety successfully added');
        }

        else{
            request()->session()->flash('error','Error occurred, Please try again!');
        }

        return redirect()->route('variety.index');


    }
    public function destroy($id)
    {
        $category=Variety::findOrFail($id);
       // $child_cat_id=Variety::where('parent_id',$id)->pluck('id');
        // return $child_cat_id;
        $status=$category->delete();

        if($status){
//            if(count($child_cat_id)>0){
//                Variety::shiftChild($child_cat_id);
//            }
            request()->session()->flash('success','Variety successfully deleted');
        }
        else{
            request()->session()->flash('error','Error while deleting category');
        }
        return redirect()->route('variety.index');
    }

    public function edit($id)
    {
        $parent_cats=Variety::get();
        $category=Variety::findOrFail($id);

        $parent_category=Category::where('is_parent',1)->get();

        return view('backend.variety.edit')->with('category',$category)->with('parent_cats',$parent_cats)->with('categories',$parent_category);
    }
    public function update(Request $request, $id)
    {
        $category=Variety::findOrFail($id);
        $this->validate($request,[
            'title'=>'string|required',
            'summary'=>'string|nullable',
            'photo'=>'max:2048',
            'status'=>'required|in:active,inactive',
            //'is_parent'=>'sometimes|in:1',
            'parent_id'=>'required',
        ]);
        $data= $request->all();
        $data['is_parent']=$request->input('is_parent',0);

        if(isset($data['photo']))
        {
            $image_original = $request->file('photo');
            $image = time().'.'.$request->photo->getClientOriginalName();
            $data['photo'] = $image;
        }

        $status=$category->fill($data)->save();
        if($status){
            if(isset($data['photo']))
            {
                $image_original->move(public_path('img/category_images'), $image);
            }
            request()->session()->flash('success','Variety successfully updated');
        }
        else{
            request()->session()->flash('error','Error occurred, Please try again!');
        }
        return redirect()->route('variety.index');
    }

}

resources/views/backend/variety/create.blade.php
@extends('backend.layouts.master')

@section('main-content')

    <div class="card">
        <h5 class="card-header">Add variety</h5>
        <div class="card-body">
            <form method="post" action="{{route('variety.store')}}" enctype="multipart/form-data" >
                {{csrf_field()}}
                <div class="form-group">
                    <label for="inputTitle" class="col-form-label">Title <span class="text-danger">*</span></label>
                    <input id="inputTitle" type="text" name="title" placeholder="Enter title"  value="{{old('title')}}" class="form-control">
                    @error('title')
                    <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="summary" class="col-form-label">Summary</label>
                    <textarea class="form-control" id="summary" name="summary">{{old('summary')}}</textarea>
                    @error('summary')
                    <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>

                {{--<div class="form-group">--}}
                {{--<label for="is_parent">Is Parent</label><br>--}}
                {{--<input type="checkbox" name='is_parent' id='is_parent' value='1' checked> Yes                        --}}
                {{--</div>--}}
                {{-- {{$parent_cats}} --}}

                {{--<div class="form-group d-none" id='parent_cat_div'>--}}
                    {{--<label for="parent_id">Parent Category</label>--}}
                    {{--<select name="parent_id" class="form-control">--}}
                        {{--<option value="">--Select any category--</option>--}}
                        {{--@foreach($parent_cats as $key=>$parent_cat)--}}
                            {{--<option value='{{$parent_cat->id}}'>{{$parent_cat->title}}</option>--}}
                        {{--@endforeach--}}
                    {{--</select>--}}
                {{--</div>--}}

                {{--<div class="form-group">--}}
                {{--<label for="inputPhoto" class="col-form-label">Photo</label>--}}
                {{--<div class="input-group">--}}
                {{--<input type="file" class="form-control" name="photo">--}}
                {{--</div>--}}
                {{--<div id="holder" style="margin-top:15px;max-height:100px;"></div>--}}

                {{--@error('photo')--}}
                {{--<span class="text-danger">{{$message}}</span>--}}
                {{--@enderror--}}
                {{--</div>--}}
                <div class="form-group">
                    <label for="parent_id">Category <span class="text-danger">*</span></label>
                    <select name="parent_id" id="parent_id" class="form-control" onchange="changeDropdown(this.value);">
                        <option value="">--Select any category--</option>
                        @foreach($categories as $key=>$cat_data)
                            <option value='{{$cat_data->id}}'>{{$cat_data->title}}</option>
                        @endforeach
                    </select>
                    @error('parent_id')
                    <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>


                <div class="form-group">
                    <label for="status" class="col-form-label">Status <span class="text-danger">*</span></label>
                    <select name="status" class="form-control">
                        <option value="active">Active</option>
                        <option value="inactive">Inactive</option>
                    </select>
                    @error('status')
                    <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>
                <div class="form-group mb-3">
                    <button type="reset" class="btn btn-warning">Reset</button>
                    <button class="btn btn-success" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>

@endsection

@push('styles')
    <link rel="stylesheet" href="{{asset('backend/summernote/summernote.min.css')}}">
@endpush
@push('scripts')
    <script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
    <script src="{{asset('backend/summernote/summernote.min.js')}}"></script>
    <script>
        $('#lfm').filemanager('image');

        $(document).ready(function() {
            $('#summary').summernote({
                placeholder: "Write short description.....",
                tabsize: 2,
                height: 120
            });
        });
    </script>

    <script>
        $('#is_parent').change(function(){
            var is_checked=$('#is_parent').prop('checked');
            // alert(is_checked);
            if(is_checked){
                $('#parent_cat_div').addClass('d-none');
                $('#parent_cat_div').val('');
            }
            else{
                $('#parent_cat_div').removeClass('d-none');
            }
        })
    </script>
@endpush

resources/views/backend/variety/edit.blade.php
@extends('backend.layouts.master')

@section('main-content')

    <div class="card">
        <h5 class="card-header">Edit variety</h5>
        <div class="card-body">
            <form method="post" action="{{route('variety.update',$category->id)}}" enctype="multipart/form-data">
                @csrf
                @method('PATCH')
                <div class="form-group">
                    <label for="inputTitle" class="col-form-label">Title <span class="text-danger">*</span></label>
                    <input id="inputTitle" type="text" name="title" placeholder="Enter title"  value="{{$category->title}}" class="form-control">
                    @error('title')
                    <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="summary" class="col-form-label">Summary</label>
                    <textarea class="form-control" id="summary" name="summary">{{$category->summary}}</textarea>
                    @error('summary')
                    <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="parent_id">Category <span class="text-danger">*</span></label>
                    <select name="parent_id" id="parent_id" class="form-control" onchange="changeDropdown(this.value);">
                        <option value="">--Select any category--</option>
                        @foreach($categories as $key=>$cat_data)
                            <option value='{{$cat_data->id}}'>{{$cat_data->title}}</option>
                        @endforeach
                    </select>
                    @error('parent_id')
                    <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>

                {{--<div class="form-group">--}}
                    {{--<label for="is_parent">Is Parent</label><br>--}}
                    {{--<input type="checkbox" name='is_parent' id='is_parent' value='{{$category->is_parent}}' {{(($category->is_parent==1)? 'checked' : '')}}> Yes--}}
                {{--</div>--}}
                {{-- {{$parent_cats}} --}}
                {{-- {{$category}} --}}

                {{--<div class="form-group {{(($category->is_parent==1) ? 'd-none' : '')}}" id='parent_cat_div'>--}}
                {{--<label for="parent_id">Parent Category</label>--}}
                {{--<select name="parent_id" class="form-control">--}}
                {{--<option value="">--Select any category--</option>--}}
                {{--@foreach($parent_cats as $key=>$parent_cat)--}}
                {{----}}
                {{--<option value='{{$parent_cat->id}}' {{(($parent_cat->id==$category->parent_id) ? 'selected' : '')}}>{{$parent_cat->title}}</option>--}}
                {{--@endforeach--}}
                {{--</select>--}}
                {{--</div>--}}

                {{--<div class="form-group">--}}
                {{--<label for="inputPhoto" class="col-form-label">Photo</label>--}}
                {{--<div class="input-group">--}}
                {{--<input type="file" class="form-control" name="photo">--}}
                {{--</div>--}}
                {{----}}
                {{--<div id="holder" style="margin-top:15px;max-height:100px;"></div>--}}
                {{--@error('photo')--}}
                {{--<span class="text-danger">{{$message}}</span>--}}
                {{--@enderror--}}
                {{--</div>--}}

                <div class="form-group">
                    <label for="status" class="col-form-label">Status <span class="text-danger">*</span></label>
                    <select name="status" class="form-control">
                        <option value="active" {{(($category->status=='active')? 'selected' : '')}}>Active</option>
                        <option value="inactive" {{(($category->status=='inactive')? 'selected' : '')}}>Inactive</option>
                    </select>
                    @error('status')
                    <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>
                <div class="form-group mb-3">
                    <button class="btn btn-success" type="submit">Update</button>
                </div>
            </form>
        </div>
    </div>

@endsection

@push('styles')
    <link rel="stylesheet" href="{{asset('backend/summernote/summernote.min.css')}}">
@endpush
@push('scripts')
    <script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
    <script src="{{asset('backend/summernote/summernote.min.js')}}"></script>
    <script>
        $('#lfm').filemanager('image');

        $(document).ready(function() {
            $('#summary').summernote({
                placeholder: "Write short description.....",
                tabsize: 2,
                height: 150
            });
        });
    </script>
    <script>
        $('#is_parent').change(function(){
            var is_checked=$('#is_parent').prop('checked');
            // alert(is_checked);
            if(is_checked){
                $('#parent_cat_div').addClass('d-none');
                $('#parent_cat_div').val('');
            }
            else{
                $('#parent_cat_div').removeClass('d-none');
            }
        })
    </script>
@endpush

resources/views/backend/variety/index.blade.php
@extends('backend.layouts.master')

@section('main-content')
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="row">
            <div class="col-md-12">
                @include('backend.layouts.notification')
            </div>
        </div>
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary float-left">Variety Lists</h6>
            <a href="{{route('variety.create')}}" class="btn btn-primary btn-sm float-right" data-toggle="tooltip" data-placement="bottom" title="Add User"><i class="fas fa-plus"></i> Add Variety</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                @if(count($categories)>0)
                    <table class="table table-bordered" id="banner-dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>S.N.</th>
                            <th>Title</th>
                            <th>Summary</th>
                            {{--<th>Is Parent</th>--}}
                            <th>Parent Category</th>
                            {{--<th>Photo</th>--}}
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>S.N.</th>
                            <th>Title</th>
                            <th>Summary</th>
                            {{--<th>Is Parent</th>--}}
                            <th>Parent Category</th>
                            {{--<th>Photo</th>--}}
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </tfoot>
                        <tbody>

                        @foreach($categories as $category)
                            @php
                                $parent_cats=DB::table('categories')->select('title')->where('id',$category->parent_id)->first();
                                $parent_cat_name = $parent_cats->title;

                            @endphp
                            <tr>
                                <td>{{$category->id}}</td>
                                <td>{{$category->title}}</td>
                                <td>{{$category->summary}}</td>
                                <td>{{$parent_cat_name}}</td>
                                {{--<td>{{(($category->is_parent==1)? 'Yes': 'No')}}</td>--}}
                                {{--<td>--}}
                                {{--@foreach($parent_cats as $parent_cat)--}}
                                {{--{{$parent_cat->title}}--}}
                                {{--@endforeach--}}
                                {{--</td>--}}
                                {{--<td>--}}
                                {{--@if($category->photo)--}}
                                {{--<img src="{{asset("img/category_images/$category->photo")}}" class="img-fluid zoom" style="max-width:80px" alt="{{$category->photo}}">--}}
                                {{--@else--}}
                                {{--<img src="{{asset('backend/img/thumbnail-default.jpg')}}" class="img-fluid" style="max-width:80px" alt="avatar.png">--}}
                                {{--@endif--}}
                                {{--</td>--}}
                                <td>
                                    @if($category->status=='active')
                                        <span class="badge badge-success">{{$category->status}}</span>
                                    @else
                                        <span class="badge badge-warning">{{$category->status}}</span>
                                    @endif
                                </td>
                                <td>
                                    <a href="{{route('variety.edit',$category->id)}}" class="btn btn-primary btn-sm float-left mr-1" style="height:30px; width:30px;border-radius:50%" data-toggle="tooltip" title="edit" data-placement="bottom"><i class="fas fa-edit"></i></a>
                                    <form method="POST" action="{{route('variety.destroy',[$category->id])}}">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-danger btn-sm dltBtn" data-id={{$category->id}} style="height:30px; width:30px;border-radius:50%" data-toggle="tooltip" data-placement="bottom" title="Delete"><i class="fas fa-trash-alt"></i></button>
                                    </form>
                                </td>
                                {{-- Delete Modal --}}
                                {{-- <div class="modal fade" id="delModal{{$user->id}}" tabindex="-1" role="dialog" aria-labelledby="#delModal{{$user->id}}Label" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                      <div class="modal-content">
                                        <div class="modal-header">
                                          <h5 class="modal-title" id="#delModal{{$user->id}}Label">Delete user</h5>
                                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                          </button>
                                        </div>
                                        <div class="modal-body">
                                          <form method="post" action="{{ route('categorys.destroy',$user->id) }}">
                                            @csrf
                                            @method('delete')
                                            <button type="submit" class="btn btn-danger" style="margin:auto; text-align:center">Parmanent delete user</button>
                                          </form>
                                        </div>
                                      </div>
                                    </div>
                                </div> --}}
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <span style="float:right">{{$categories->links()}}</span>
                @else
                    <h6 class="text-center">No Categories found!!! Please create Category</h6>
                @endif
            </div>
        </div>
    </div>
@endsection

@push('styles')
    <link href="{{asset('backend/vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <style>
        div.dataTables_wrapper div.dataTables_paginate{
            display: none;
        }
    </style>
@endpush

@push('scripts')

    <!-- Page level plugins -->
    <script src="{{asset('backend/vendor/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('backend/vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="{{asset('backend/js/demo/datatables-demo.js')}}"></script>
    <script>

        $('#banner-dataTable').DataTable( {
            "columnDefs":[
                {
                    "orderable":false,
                    "targets":[3,4,5]
                }
            ]
        } );

        // Sweet alert

        function deleteData(id){

        }
    </script>
    <script>
        $(document).ready(function(){
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $('.dltBtn').click(function(e){
                var form=$(this).closest('form');
                var dataID=$(this).data('id');
                // alert(dataID);
                e.preventDefault();
                swal({
                    title: "Are you sure?",
                    text: "Once deleted, you will not be able to recover this data!",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                    .then((willDelete) => {
                        if (willDelete) {
                            form.submit();
                        } else {
                            swal("Your data is safe!");
                        }
                    });
            })
        })
    </script>
@endpush